### ISSUE TITLE
Run container with 2 bootnodes and 6 validators

### ISSUE THREAD

**Issue by yehia67** [PegaSysEng/besu-sample-networks#78]
Hello, I have a question. I am planning to use your docker container to run an ibft2 algorithm for production. So I need to have 2 bootnodes and 6 validators. On` docker-compose_poa.yml` you have only one bootnode and three validators. Is it possible to modify this file?  Is it a good idea? If not what alternatives do you suggest?
Thanks.

**Comment by joshuafernandes** [comment]
Hello @yehia67 

The examples here are examples to help users get started quickly and understand how things work, so they can build their production network based on their requirements. By all means welcome to fork the repo and create configs to suit your env. 

To start with I'd recommend following this [section](https://besu.hyperledger.org/en/stable/Tutorials/Private-Network/Create-IBFT-Network/) to create a genesis file and validator keys

Our production guidelines are in the 'Deploy to Production' [section](https://besu.hyperledger.org/en/stable/HowTo/Deploy/Bootnodes/)

I would recommend getting familiar with that section, setting up bootnodes etc and then deploying your production network to mulitple instances/VMs rather than a single machine. 

Cheers

**Comment by yehia67** [comment]
Okay Thank you very much @joshuafernandes
